[package]
org = "admin"
name = "sample_project_2"
version = "0.1.0"
distribution = "2201.13.1"

[[dependency]]
org = "ballerinax"
name = "wso2.apim.catalog"
version = "1.2.1"
repository = "local"

[build-options]
remoteManagement=true
