[package]
org = "ballerinax"
name = "apim_catalog_tests"
version = "1.2.1"

[[dependency]]
org = "ballerinax"
name = "wso2.apim.catalog"
version = "1.2.1"
repository="local"

[build-options]
remoteManagement=true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina"
artifactId = "wso2.apim.catalog-native"
version = "1.2.1"
path = "../native/build/libs/wso2.apim.catalog-native-1.2.1-SNAPSHOT.jar"
