[plugin]
id = "wso2.apim.catalog-compiler-plugin"
class = "io.ballerina.wso2.apim.catalog.ServiceCatalogCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/wso2.apim.catalog-compiler-plugin-1.2.1-SNAPSHOT.jar"

[[dependency]]
path = "lib/ballerina-to-openapi-2.4.0.jar"

[platform.java21]
graalvmCompatible = true
